### ISSUE TITLE
unreachable panicked in tower-lsp

### ISSUE THREAD

**Issue by ModProg** [ebkalderon/tower-lsp#413]
I got the following error, but am unsure what caused it.
```
thread 'main' panicked at /home/modprog/.cargo/git/checkouts/tower-lsp-f49cd339669d4ee2/ad8f1ec/src/transport.rs:120:60:\n
internal error: entered unreachable code\n
stack backtrace:\n
   0: rust_begin_unwind\n
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5\n
   1: core::panicking::panic_fmt\n
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14\n
   2: core::panicking::panic\n
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5\n
   3: tower_lsp::transport::Server<I,O,L>::serve::{{closure}}::{{closure}}\n
             at /home/modprog/.cargo/git/checkouts/tower-lsp-f49cd339669d4ee2/ad8f1ec/src/transport.rs:120:60\n
   4: <futures_util::sink::map_err::SinkMapErr<Si,F> as futures_sink::Sink<Item>>::poll_ready::{{closure}}\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/sink/map_err.rs:38:65\n
   5: core::task::poll::Poll<core::result::Result<T,E>>::map_err\n
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/task/poll.rs:149:52\n
   6: <futures_util::sink::map_err::SinkMapErr<Si,F> as futures_sink::Sink<Item>>::poll_ready\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/sink/map_err.rs:38:9\n
   7: <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/forward.rs:55:24\n
   8: <futures_util::stream::stream::Forward<St,Si> as core::future::future::Future>::poll\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13\n
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:55:37\n
  10: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13\n
  11: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/maybe_done.rs:95:38\n
  12: tower_lsp::transport::Server<I,O,L>::serve::{{closure}}::{{closure}}\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/async_await/join_mod.rs:95:13\n
  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/poll_fn.rs:56:9\n
  14: tower_lsp::transport::Server<I,O,L>::serve::{{closure}}\n
             at /home/modprog/.cargo/git/checkouts/tower-lsp-f49cd339669d4ee2/ad8f1ec/src/transport.rs:163:9\n
  15: ltex_lsp_rust::main::{{closure}}\n
             at ./src/main.rs:119:59\n
  16: tokio::runtime::park::CachedParkThread::block_on::{{closure}}\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:63\n
  17: tokio::runtime::coop::with_budget\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:107:5\n
  18: tokio::runtime::coop::budget\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:73:5\n
  19: tokio::runtime::park::CachedParkThread::block_on\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:31\n
  20: tokio::runtime::context::blocking::BlockingRegionGuard::block_on\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/blocking.rs:66:9\n
  21: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:87:13\n
  22: tokio::runtime::context::runtime::enter_runtime\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/runtime.rs:65:16\n
  23: tokio::runtime::scheduler::multi_thread::MultiThread::block_on\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:86:9\n
  24: tokio::runtime::runtime::Runtime::block_on\n
             at /home/modprog/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/runtime.rs:350:45\n
  25: ltex_lsp_rust::main\n
             at ./src/main.rs:107:5\n
  26: core::ops::function::FnOnce::call_once\n
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5\n
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n
````

**Comment by irevoire** [comment]
Hey, I’m getting this one a lot as well

**Comment by sreyassabbani** [comment]
So this bug also affects `postgrestools`'s LSP. I got this error message while trying to use it:

```
This is a bug in Postgres Tools, not an error in your code, and we would appreciate it if you could report it along with the following information to help us fixing the issue:

Source Location: /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-lsp-0.20.0/src/transport.rs:120:60
Thread Name: tokio-runtime-worker
Message: internal error: entered unreachable code
```

I've also opened up [a discussion](https://github.com/supabase-community/postgres-language-server/discussions/446) in the `postgrestools` repo, btw.
